# Default configuration for Face Parsing model

# Data configuration
data:
  data_dir: ./data
  image_size: [512, 512]
  batch_size: 8
  num_workers: 4
  augmentation: true
  train_val_split: 0.9

# Model configuration
model:
  num_classes: 19  # CelebAMask-HQ classes
  backbone: resnet50  # Placeholder - to be implemented
  pretrained: true
  
# Training configuration  
training:
  max_epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0001
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  
# Optimizer configuration
optimizer:
  type: AdamW
  betas: [0.9, 0.999]
  eps: 1e-08

# Scheduler configuration
scheduler:
  type: CosineAnnealingLR
  T_max: 100
  eta_min: 1e-06
  
# Loss configuration
loss:
  type: CrossEntropyLoss
  ignore_index: 255
  weight: null  # Can add class weights if needed
  
# Callbacks configuration
callbacks:
  checkpoint:
    monitor: val/iou
    mode: max
    save_top_k: 3
    save_last: true
  early_stopping:
    monitor: val/loss
    patience: 15
    mode: min
    
# Experiment configuration
experiment:
  name: face_parsing_baseline
  seed: 42
  deterministic: true
  
# Hardware configuration
hardware:
  gpus: 1
  accelerator: auto
  precision: 16-mixed  # Use mixed precision if available
  
# Logging configuration
logging:
  log_every_n_steps: 10
  val_check_interval: 1.0
  log_dir: ./experiments/logs
  
# Dataset specific configuration
dataset:
  name: CelebAMask-HQ
  classes:
    - background
    - skin
    - l_brow
    - r_brow
    - l_eye
    - r_eye
    - eye_g
    - l_ear
    - r_ear
    - ear_r
    - nose
    - mouth
    - u_lip
    - l_lip
    - neck
    - neck_l
    - cloth
    - hair
    - hat